ruby '1.9.3'
source 'https://rubygems.org'
gem 'sinatra', '>= 0'
gem 'haml', '>= 0'
gem 'json', '>= 0'
gem 'mongo', '>= 1.9.2'
gem 'github-oauth', '>= 0'
gem 'github-api', '>= 0'
gem 'bson_ext', '>= 0'
